server:
  port: 8761

#微服务名称
spring:
  application:
    name: demo-gateway
  datasource:
    name: gateway
    url: jdbc:mysql://localhost:3306/spring-security?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
#      routes:
#        #路径匹配
#        - id: demo-server
#          uri: lb://demo-server
#          predicates:
#            - Path=/api/hi/**
#          filters:
#            - RewritePath=/api/(?<segment>.*), /$\{segment}
#            - AddRequestHeader=X-Request-Foo, Bar

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/

mybatis-plus:
  mapper-locations: classpath:com/bruce/demo/gateway/sqlmap/auto/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoint:
    caches:
      enabled: true
    prometheus:
      enabled: true
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,gateway,caches,beans